server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Raisaabshailen/Springcloud-congif.git
          clone-on-start: true
